--PRODUCT DISCOUNT
SET SERVEROUTPUT ON
DECLARE
	P_NAME CHAR(10):='&P_NAME';
	P_TY NUMBER(10):=&P_TY;
	P_PRICE NUMBER(10):=&P_PRICE;
	DISCOUNT NUMBER(10);
	TOTAL NUMBER(10);
BEGIN
	TOTAL:=P_PRICE*P_TY;
	DISCOUNT:=TOTAL*25/100;
	DBMS_OUTPUT.PUT_LINE('DISCOUNT IS='||DISCOUNT);
END;
/